OPENAI_API_KEY = "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"   # Replace with your actual OpenAI key
